// Auto-generated by tools/generate-content.mjs
// Do not edit manually.

export const content = [
  { id: 1, src: "./assets/img/Story%20-%201.png", alt: "Story - 1" },
  { id: 2, src: "./assets/img/Story%20-%202.png", alt: "Story - 2" },
  { id: 3, src: "./assets/img/Story%20-%203.png", alt: "Story - 3" },
  { id: 4, src: "./assets/img/Story%20-%204.png", alt: "Story - 4" },
  { id: 5, src: "./assets/img/Story%20-%205.png", alt: "Story - 5" },
  { id: 6, src: "./assets/img/Story%20-%206.png", alt: "Story - 6" },
  { id: 7, src: "./assets/img/Story%20-%207.png", alt: "Story - 7" },
  { id: 8, src: "./assets/img/Story%20-%208.png", alt: "Story - 8" },
  { id: 9, src: "./assets/img/Story%20-%209.png", alt: "Story - 9" },
];
