import fs from "fs";
import path from "path";
import { fileURLToPath } from "url";

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const ROOT = path.resolve(__dirname, "..");
const ASSETS_IMG = path.join(ROOT, "assets", "img");
const OUTPUT = path.join(ROOT, "src", "core", "content.js");

const IMAGE_EXTS = new Set([
  ".jpg", ".jpeg", ".png", ".gif", ".webp", ".svg", ".avif", ".bmp",
]);

function scanDir(dirPath, urlPrefix) {
  const results = [];
  try {
    const entries = fs.readdirSync(dirPath, { withFileTypes: true });
    for (const entry of entries) {
      if (!entry.isFile()) continue;
      const ext = path.extname(entry.name).toLowerCase();
      if (!IMAGE_EXTS.has(ext)) continue;
      const nameWithoutExt = path.basename(entry.name, ext);
      const src = encodeURI(urlPrefix + "/" + entry.name);
      results.push({ name: nameWithoutExt, type: "image", src, alt: nameWithoutExt });
    }
  } catch (e) {
    if (e.code !== "ENOENT") {
      console.warn(`  ⚠ Error leyendo ${dirPath}: ${e.message}`);
    }
  }
  return results;
}

const slides = scanDir(ASSETS_IMG, "./assets/img");

slides.sort((a, b) => a.name.localeCompare(b.name, "es"));

let code = "// Auto-generated by tools/generate-content.mjs\n";
code += "// Do not edit manually.\n\n";
code += "export const content = [\n";

slides.forEach((slide, i) => {
  code += `  { id: ${i + 1}, src: "${slide.src}", alt: "${slide.alt}" },\n`;
});

code += "];\n";

fs.writeFileSync(OUTPUT, code, "utf-8");
console.log(`✓ Generado ${OUTPUT} con ${slides.length} slide(s).`);
